import '@shgysk8zer0/components/share-button.js';
import '@shgysk8zer0/components/button/share-to.js';
import '@shgysk8zer0/components/weather/current.js';
import '@kernvalley/components/events.js';
// import '@shgysk8zer0/components/slide-show/slide-show.js';
import '@shgysk8zer0/components/github/user.js';
import '@shgysk8zer0/components/current-year.js';
import '@shgysk8zer0/components/bacon-ipsum.js';
import '@shgysk8zer0/components/install/prompt.js';
// import '@kernvalley/components/ad.js';
// import '@shgysk8zer0/components/app/list-button.js';
import '@shgysk8zer0/components/app/stores.js';
// import './components/firebase-sign-in.js';
// import './components/firebase-sign-up.js';
// import './components/firebase-password-reset.js';
// import './components/firebase-confirm-reset.js';
import '@shgysk8zer0/components/firebase/auth/sign-in.js';
import '@shgysk8zer0/components/firebase/auth/sign-up.js';
import '@shgysk8zer0/components/firebase/auth/password-reset.js';
import '@shgysk8zer0/components/firebase/auth/confirm-reset.js';
import '@shgysk8zer0/components/firebase/auth/verify-email.js';
import '@shgysk8zer0/components/firebase/auth/email-link.js';
import '@shgysk8zer0/components/firebase/auth/change-password.js';
