# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./_site"
  command = "npm run build && npm run build:site"
  functions = "api"
[dev]
  base = "./"
  publish = "./_site"
  command = "npm run serve:dev"
  functions = "api"
  targetPort = 8080
[functions]
  external_node_modules = ["@shgysk8zer0/slack", "@shgysk8zer0/consts", "@shgysk8zer0/netlify-func-utils", "@shgysk8zer0/http"]
  node_bundler = "esbuild"
