name: KRV Bridge Connection
shortName: KRV Bridge
# version: 2.0.0
lang: en
dir: ltr
display: standalone
orientation: any
# description: "A GitHub repository for easily creating fast, modern, PWA compatible websites"
icons-file: /img/icons.svg
theme:
  color: '#1a5fb4'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: 'https://i.imgur.com/IjdVouxh.png'
    sizes: 1024x502
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxl.png'
    sizes: 640x314
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxm.png'
    sizes: 320x157
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxt.png'
    sizes: 160x78
    type: image/png
# https://web.dev/app-shortcuts/
shortcuts:
  - name: Resources
    description: Directory of Resources
    url: /resources/
    icons:
    - src: /img/shortcuts/resources.svg
      sizes: 192x192
      type: image/svg+xml
    - src: /img/shortcuts/resources-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/resources-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/resources-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/resources-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/resources-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/resources-36.png
      sizes: 36x36
      type: image/png
  - name: Contact
    description: Contact KRV Bridge Connection
    url: /contact/
    icons:
    - src: /img/shortcuts/contact.svg
      sizes: 192x192
      type: image/svg+xml
    - src: /img/shortcuts/contact-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/contact-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/contact-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/contact-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/contact-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/contact-36.png
      sizes: 36x36
      type: image/png
  - name: About
    description: About KRV Bridge Connection
    url: /about/
    icons:
    - src: /img/shortcuts/about.svg
      sizes: 192x192
      type: image/svg+xml
    - src: /img/shortcuts/about-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/about-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/about-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/about-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/about-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/about-36.png
      sizes: 36x36
      type: image/png
share_target:
  name: Contact Page
  action: "/contact/"
  enctype: application/x-www-form-urlencoded
  method: GET
  params:
    title: subject
    text: body
iarc_rating_id: dd768f7f-8541-4555-a447-f07338b2d4aa
related_applications:
  - platform: webapp
    url: /webapp.webmanifest
  - platform: play
    id: "org.krvbridge.twa"
    url: "https://play.google.com/store/apps/details?id=org.krvbridge.twa"
  # - platform: itunes
  #   url: "#"
  # - platform: windows
  #   url: "#"
features:
  - PWA-ready GitHub template for Jekyll sites
  - Dark mode support, controlled by (prefers-color-scheme) media query
  - Includes templates created with SEO via structured data in mind
  - Initial setup scores 99% on mobile on Page Speed Insights
  - Responsive design supporting any screen size thanks to CSS grid and use of viewport units
  - Integtation with system sharing via the Share API (with fallback)
  - Preset Pull Request and Issue templates, as well as Code of Conduct & Contributing Guidelines
  - Built-in testing via GitHub Actions, eslint, and stylelint
  - Always up-to-date thanks to preset Dependabot-v2 config
  - Setup for quick deployment to Netlify
  - Version files for NodeJS (.nvmrc)
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - business
  - productivity
  - utilities

