---
title: 'KRV Bridge Connection'
description: 'A directory of helpful services for the KRV'
repository:
  username: 'KRV-Bridge-Connection'
  project: 'krv-bridge-connection'
url: 'https://krvbridge.org/'
viewport: 'width=device-width'
referrer: 'no-referrer'
color-scheme: 'light dark'
og-type: 'website'
base: '/'
manifest: '/webapp.webmanifest'
service_worker: '/service-worker.js'
keep-kern-clean: false
